<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GymTron.Api\GymTron.Api.csproj" />
    <ProjectReference Include="..\..\src\GymTron.Application\GymTron.Application.csproj" />
    <ProjectReference Include="..\..\src\GymTron.Domain\GymTron.Domain.csproj" />
    <ProjectReference Include="..\..\src\GymTron.Infrastructure\GymTron.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\src\GymTron.App\Services\Api\Models\ApiModels.cs" Link="App\ApiModels.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\TrainingViewModel.cs" Link="App\TrainingViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\TrainingDateViewModel.cs" Link="App\TrainingDateViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\RoutineItemViewModel.cs" Link="App\RoutineItemViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\ExerciseViewModel.cs" Link="App\ExerciseViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\ExerciseParametersViewModel.cs" Link="App\ExerciseParametersViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\Helpers\TextEncodingHelper.cs" Link="App\TextEncodingHelper.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\RangeViewModel.cs" Link="App\RangeViewModel.cs" />
    <Compile Include="..\..\src\GymTron.App\ViewModels\Entities\ObservationViewModel.cs" Link="App\ObservationViewModel.cs" />
  </ItemGroup>

</Project>
